### PR TITLE
Travis & Standard

### PR DESCRIPTION
**Pull request by ngoldman**
* added .travis.yml
* activated travis-ci for this repo
* added build status to readme
* style rewrite for standard

:v:

### CODE REVIEW

**Comment by chelm** [comment]
@ngoldman have turned on travis for this repo?

**Comment by chelm** [comment]
I'll do it now

**Comment by chelm** [comment]
oh duh its right there

**Comment by ngoldman** [comment]
@chelm thanks! I'm going to add a change log (just noticed I forgot to create one) then bump this repo to 1.0.0 unless there are any objections.

**Comment by chelm** [comment]
@ngoldman sounds good.

**Pull request merged**
